import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import Link from "next/link";
import Sidebar from "@/components/admin/Sidebar";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
         <Toaster position="top-center" richColors />
        <div className="min-h-screen">
          {/* Top Navbar */}
          {/* <header className="bg-gray-800 text-white px-6 py-3 fixed w-full top-0 z-50 shadow-md">
            <div className="max-w-7xl mx-auto flex justify-between items-center">
              <h1 className="text-lg font-semibold">Admin Panel</h1>
            </div>
          </header> */}

          <div className="flex w-full">
            {/* Sidebar */}
            <Sidebar />

              {/* Main content */}
              <main className=" bg-gray-100 min-h-screen w-full">
                {children}
              </main>
              {/* <Sidebar /> */}
            </div>

          {/* Footer */}
          <footer className="bg-gray-200 text-center text-sm text-gray-600 py-4">
            © {new Date().getFullYear()} Admin Dashboard. All rights reserved.
          </footer>
        </div>
      </body>
    </html>
  );
}
