import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { AuthProvider } from "../../context/AuthContext";
import Link from "next/link";
import Navbar from "@/components/layouts/Navbar";
import { Toaster } from 'sonner';
import Footer from "@/components/layouts/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <Toaster position="top-center" richColors />
          <div className="flex flex-col min-h-screen">
            {/* Navbar */}
            <Navbar />

            {/* Main Content */}
            <main className="flex-1">{children}</main>

            {/* Footer */}
            {/* <footer className="bg-white border-t py-4 text-center text-sm text-gray-500">
              &copy; {new Date().getFullYear()} MyApp. All rights reserved.
            </footer> */}
            <Footer />
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
